### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by arena-sh** [nQuake/nquake.github.io#12]
http://nquake.com and http://nquake.github.io is not opening up as of today

**Comment by liback** [comment]
It's only when explicitly requesting the non-https version of the site that it doesn't serve anything, I.e. typing nquake.com or www.nquake.com works as they'll serve the https version.

Would be nice to have the http url serve the https version though as I guess there may be old links all over the web being broken now.

Edit: perhaps it was even more broken before and empezar did some magic since. :)

**Comment by arena-sh** [comment]
@liback it was all HTTP before the magic :) Proof: even with HTTPS, youtube wouldn't work anymore (which currently, doesn't) because of loading content from HTTP wouldn't be allowed when using Firefox (I've sent #14 to fix them). If you decide to drop www again, I can make another PR for fixing the internal references.

**Comment by niclaslindstedt** [comment]
nquake.com without www doesn't work for me yet, still.

I think it's a DNS issue.

**Comment by arena-sh** [comment]
Just tested following redirects, all working:
http://nquake.com -> https://www.nquake.com
https://nquake.com -> https://www.nquake.com
http://www.nquake.com -> https://www.nquake.com
