### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by liback** [nQuake/nquake.github.io#18]
Get Quad
- Goes to the old website (new season 5 hosted on Wiki)

Thunderdome
- Should link to https://td.quakeworld.ru/?sid=143

QHLAN
- Site down? Remove?

Fnu.nu
- Down?

NQuake twitter
- Account nquakeworld doesn't seem  to exist

**Comment by eb** [comment]
QHLAN site was erroring out at one point and Zalon told me to simply shut it down for now.
I am sure it would be revived once there's a QHLAN, but when that might be, I dunno.
Maybe all the event sites should be removed and simply replaced by a wiki link there, since you can find all on-going events easily on its main page.
